using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProCSharpCode
{
    // differences between .net framework and .net core
    // ------------------------------------------------------
    // 1- .net framework targets microsoft OS, but core is cross platform
    // 2- .net core has AssemblyLoadContext , and it wasn't exist in .net framework
    // 3- .net framwork allow to to write assemblyinfo.cs file but .net core doesn't, it is autogenerated
    //    by the compiler.
    // 
    // 4- .NET Core does not support multifile assemblies.
    // 5- .NET Core has only one AppDomain in the process, and that is not the case
    //      in .NET Framework, (the problem of os support, and it is expensive to create)
    //      so , System.AppDomain is Deprecated.
}
